mysql:
  username: root
  password: 930619
  database: data-space
  host: 127.0.0.1
  port: 3306
  charset: utf8mb4
  max-idle-connections: 10
  max-open-connections: 30
  max-connection-life-time: 1h
  log-level: 1

jwt:
  secret: hexiaopi
  issuer: data-space
  expire: 1h